pipeline {
    
    agent any
    tools {
        go '1.19.4'
    }
    environment {
        GO114MODULE = 'on'
        CGO_ENABLED = 0
        GOPATH = "${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}"
    }
    stages {
        stage('Pre Test') {
            steps {
                echo 'Installing dependencies'
                sh 'go version'
                sh 'cd ./cidr_convert_api/go/'
                sh 'go get -u golang.org/x/lint/golint'
                sh 'go get github.com/Pepegasca/goop'
            }
        }
        stage('Static Code Analysis (SonarQube)') {
            steps {
                sh 'Here goes Static Code Analysis'
            }
        }
        stage('Example') {
            steps {
                sh 'echo ***********GO VERSION*******************'
                sh 'go version'
            }
        }
    }
}